"""add_subscribes

Revision ID: 832b91142f33
Revises: d120352e2e3e
Create Date: 2025-01-23 08:23:37.993467

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "832b91142f33"
down_revision = "d120352e2e3e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscribes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artikul", sa.BIGINT(), nullable=False),
        sa.Column("last_update", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artikul"], ["products.artikul"], name=op.f("subscribes_artikul_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("subscribes_pkey")),
    )
    with op.batch_alter_table("subscribes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("subscribes_id_idx"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscribes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("subscribes_id_idx"))

    op.drop_table("subscribes")
    # ### end Alembic commands ###
